mobile_settings_module:
  name: Mobile Settings Module
  version: '1.0'
  creator: ''
  supported:
    - button
    - climate
    - cover
    - horizontal-buttons-stack
    - media-player
    - pop-up
    - select
    - separator
    - sub-buttons
  description: ''
  code: |-
      ha-card {
      --bubble-main-background-color: var(--background-color-2) !important;
      --bubble-accent-color: var(--slate-color) !important;
      border-radius: 15px !important;
      margin: 2px 5px 2px 5px !important;
      }

      .bubble-button-background {
        background-color: ${state === 'on' ? 'var(--slate-color)' : 'var(--background-color-2)'} !important;
        border-radius: 15px !important;
        opacity: 1 !important;
        }

      .bubble-button-card-container {
        border-radius: 15px !important;
        margin: 2px 5px 2px 5px !important;
        background-color: ${state === 'on' ? 'var(--slate-color)' : 'var(--background-color-2)'} !important;
        opacity: 1 !important;
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.25) !important;
      }

      .bubble-name { 
        font-size: 16px !important;
        text-align: left !important;
        color: ${state === 'on' ? 'var(--primary-background-color)' : 'var(--primary-text-color)'} !important;
        } 

      .bubble-state {
        font-size: 14px !important;
        text-align: left !important;
        color: ${state === 'on' ? 'var(--primary-background-color)' : 'var(--primary-text-color)'} !important;
        } 
        
      .bubble-icon-container {
      background: transparent !important;
      }
      
      .bubble-sub-button {
        font-size: 14px !important;
        font-weight: bold;
        margin-right: 10px;
        background: transparent !important;
        color: ${state === 'on' ? 'var(--primary-background-color)' : 'var(--secondary-text-color)'} !important;
      }
      
      .bubble-icon {
      opacity: 1 !important;
      color: ${state === 'on' ? 'var(--primary-background-color)' : 'var(--primary-text-color)'} !important;
      }
  editor: ''
