
# Loads default set of integrations. Do not remove.
default_config:

my:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit: !include homekit.yaml
template: !include sensors2.yaml

group:
  smartphones:
    name: "Smartphones"
    entities:
      - device_tracker.brians_iphone_15_pro
      - device_tracker.carmens_iphone

input_datetime:
  last_pool_vacuum:
    name: Last Pool Vacuum
    has_date: true
    has_time: true

input_number:
  sonos_favorites_index:
    name: Sonos Favorites Index
    initial: 1
    min: 1
    max: 11
    step: 1
    mode: box

input_boolean:
  sonos_group_select_living_room:
    name: Group Living Room
    icon: mdi:sofa
  sonos_group_select_kitchen:
    name: Group Kitchen
    icon: mdi:countertop
  sonos_group_select_office:
    name: Group Office
    icon: mdi:desk
  sonos_group_select_deck:
    name: Group Deck
    icon: mdi:table-chair
  sonos_group_select_pool:
    name: Group Pool
    icon: mdi:pool
  sonos_group_select_primary_bedroom:
    name: Group Primary Bedroom
    icon: mdi:bed
  sonos_group_select_primary_bathroom:
    name: Group Primary Bathroom
    icon: mdi:shower
  sonos_group_select_gym:
    name: Group Gym
    icon: mdi:dumbbell
  sonos_group_select_mud_room:
    name: Group Mud Room
    icon: mdi:door
  sonos_group_select_media_room:
    name: Group Media Room
    icon: mdi:television

input_select:
  sonos_speaker_select:
    name: Sonos Speaker
    options:
      - Living Room
      - Kitchen
      - Office
      - Deck
      - Pool
      - Primary Bedroom
      - Primary Bathroom
      - Gym
      - Mud Room
      - Media Room
    initial: Living Room
    icon: mdi:speaker
  sonos_group_coordinator:
    name: Sonos Group Coordinator
    options:
      - living_room
      - kitchen
      - office
      - deck
      - pool
      - primary_bedroom
      - primary_bathroom
      - gym
      - mud_room
      - media_room
    initial: living_room
    icon: mdi:speaker-multiple
  sonos_favorites_filter:
    name: Sonos Favorites Filter
    options:
      - All
      - Playlists
      - Stations
      - Albums
    initial: All
    icon: mdi:filter-variant

input_text:
  sonos_favorites_search:
    name: Sonos Favorites Search
    initial: ""
    max: 60
    icon: mdi:magnify

utility_meter:
  daily_well_pump:
    source: sensor.well_pump_energy2
    cycle: daily
  daily_ev_charger:
    source: sensor.wall_charger_energy
    cycle: daily

recorder:
  db_url: mysql://carmenv:Bayberry1991@core-mariadb/homeassistant?charset=utf8mb4
  purge_keep_days: 30
  exclude:
    domains:
      - media_player
    entity_globs:
      - sensor.time*
      - binary_sensor.*_person_detected*
      - binary_sensor.*_vehicle_detected*
      - binary_sensor.*_animal_detected*
      - binary_sensor.*_object_detected*
      - binary_sensor.*_audio_object_detected*
      - binary_sensor.*_speaking_detected*
      - binary_sensor.*_barking_detected*
      - binary_sensor.*_siren_detected*
      - binary_sensor.*_smoke_alarm_detected*
      - binary_sensor.*_car_horn_detected*
      - binary_sensor.*_car_alarm_detected*
      - sensor.*_last_motion_detected*
      - switch.*_detections_person
      - switch.*_detections_vehicle
      - switch.*_detections_animal
      - switch.*_detections_speaking
      - sensor.bedroom_air_quality*
      - sensor.first_floor_air_quality_monitor*
    
    entities:
      - sensor.date
      - sensor.time
      - sensor.last_boot
      - sun.sun 
      - sensor.powerwall_discharge_time
      - sensor.bayberry_tempest_wind_speed
      - sensor.bayberry_tempest_wind_direction
      - binary_sensor.myggspray_wrlss_mtn_sensor_occupancy
      - sensor.myggspray_wrlss_mtn_sensor_battery
      - sensor.myggspray_wrlss_mtn_sensor_battery_voltage
      - sensor.myggspray_wrlss_mtn_sensor_battery_type
      - sensor.myggspray_wrlss_mtn_sensor_illuminance
      - update.myggspray_wrlss_mtn_sensor_firmware
      - button.myggspray_wrlss_mtn_sensor_identify_1
      - button.myggspray_wrlss_mtn_sensor_identify_2  
      - binary_sensor.myggspray_wrlss_mtn_sensor_occupancy_2
      - sensor.myggspray_wrlss_mtn_sensor_battery_2
      - sensor.myggspray_wrlss_mtn_sensor_battery_voltage_2
      - sensor.myggspray_wrlss_mtn_sensor_battery_type_2
      - sensor.myggspray_wrlss_mtn_sensor_illuminance_2
      - update.myggspray_wrlss_mtn_sensor_firmware_2
      - button.myggspray_wrlss_mtn_sensor_identify_1_2
      - button.myggspray_wrlss_mtn_sensor_identify_2_2



lovelace_gen:

lovelace:
  resource_mode: yaml
  dashboards:
    first-floor-dash:
      mode: yaml
      title: "First Floor - YAML"
      icon: mdi:floor-plan
      show_in_sidebar: false
      filename: first_floor_dash/first_floor.yaml
    mobile-dash:
      mode: yaml
      title: "Mobile - YAML"
      icon: mdi:cellphone
      show_in_sidebar: true
      filename: dashboards/mobile/mobile.yaml 
    desktop-dash:
      mode: yaml
      title: "Desktop - YAML"
      icon: mdi:desktop-classic
      show_in_sidebar: true
      filename: dashboards/desktop/desktop.yaml 
    mudroom-wall-panel-dash:
      mode: yaml
      title: Mudroom Wall Panel - YAML
      icon: mdi:alarm-panel
      show_in_sidebar: true
      filename: dashboards/wall-panel/mudroom-wall-panel.yaml
    living-room-wall-panel-dash:
      mode: yaml
      title: "Living Room Wall Panel - YAML"
      icon: mdi:alarm-panel
      show_in_sidebar: true
      filename: dashboards/wall-panel-v2/living-room-wall-panel.yaml
  resources: 
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/kiosk-mode/kiosk-mode.js
      type: module
    - url: /hacsfiles/Bubble-Card/bubble-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/power-flow-card-plus/power-flow-card-plus.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /browser_mod.js
      type: module      
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module 
    - url: /hacsfiles/lovelace-expander-card/expander-card.js 
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js 
      type: module
    - url: /hacsfiles/llmvision-card/llmvision-card.js 
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js  
      type: module    
    - url: /hacsfiles/custom-sonos-card/custom-sonos-card.js
      type: module
    - url: /hacsfiles/simple-swipe-card/simple-swipe-card.js
      type: module
    - url: /hacsfiles/Ultra-Vehicle-Card/ultra-vehicle-card.js 
      type: module
    - url: /hacsfiles/alarmo-card/alarmo-card.js 
      type: module
    - url: /hacsfiles/apexcharts-card/apexcharts-card.js 
      type: module
    - url: /hacsfiles/weather-radar-card/weather-radar-card.js 
      type: module 
    - url: /hacsfiles/energy-sankey/energy-sankey.js 
      type: module
    - url: /hacsfiles/mediocre-hass-media-player-cards/mediocre-hass-media-player-cards.js
      type: module
    - url: /hacsfiles/config-template-card/config-template-card.js
      type: module
    - url: /hacsfiles/weather-forecast-card/weather-forecast-card.js
      type: module
    - url: /hacsfiles/custom-sonos-card-v2/custom-sonos-card-v2.js
      type: module
    - url: /hacsfiles/custom-media-card/wall-panel-sonos-card.js
      type: module      

sensor:
  - platform: filter
    name: "Bedroom CO2 (5min)"
    entity_id: sensor.bedroom_air_quality_carbon_dioxide
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "Bedroom Humidity (5min)"
    entity_id: sensor.bedroom_air_quality_humidity
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "Bedroom PM2.5 (5min)"
    entity_id: sensor.bedroom_air_quality_pm2_5
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "Bedroom Temperature (5min)"
    entity_id: sensor.bedroom_air_quality_temperature
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "First Floor CO2 (5min)"
    entity_id: sensor.first_floor_air_quality_monitor_carbon_dioxide
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "First Floor Humidity (5min)"
    entity_id: sensor.first_floor_air_quality_monitor_humidity
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "First Floor PM2.5 (5min)"
    entity_id: sensor.first_floor_air_quality_monitor_pm2_5
    filters:
      - filter: time_throttle
        window_size: "00:05"
  - platform: filter
    name: "First Floor Temperature (5min)"
    entity_id: sensor.first_floor_air_quality_monitor_temperature
    filters:
      - filter: time_throttle
        window_size: "00:05"

rest_command:
  update_live_activity:
    url: 'https://api.getaivi.app/activity/{{ slug }}'
    method: PATCH
    headers:
      content-type: application/json
      authorization: Token 061c26af03cf0c109daca036d22ff768
    payload: '{{ payload }}'