set_hold_time:
  description: "Set the hold time for the thermostat."
  target:
    entity:
      domain: climate
  fields:
    time_period:
      description: "Time period for hold."
      example: "01:00:00"
      required: true
      selector:
        text:

set_room_priority:
  description: "Set the room priority for the thermostat to one or more rooms."
  target:
    entity:
      domain: climate
  fields:
    room_names:
      description: "A list of room names to prioritize."
      example:
        - "Living Room"
        - "Bedroom"
      required: true
      selector:
        object:

set_ventilation_timer:
  description: "Set the ventilation timer duration."
  target:
    entity:
      domain: fan
  fields:
    duration:
      name: Duration
      description: "Duration in minutes for the ventilation timer"
      required: true
      example: 15
      selector:
        number:
          min: 1
          max: 240
          unit_of_measurement: "minutes"