title: Settings
icon: mdi:cog
theme: Bubble
path: settings
type: custom:grid-layout
cards:
  - type: custom:button-card
    styles:
      card:
        - border-radius: 15px
        - padding-bottom: 5px
        - padding-left: 5px
        - padding-right: 10px
        - padding-top: 2px
        - margin: -8px
        - height: auto
        - width: 398px
      grid:
        - grid-template-areas: |
            "header"
            "chips"
            "settings"
        - grid-template-columns: auto
        - grid-template-rows: 60px 60px auto auto
        - row-gap: 0px
        - align-items: start
        - column-gap: 2px
    custom_fields:
      header:
        card:
          type: custom:button-card
          show_state: false
          show_name: false
          show_icon: false
          styles:
            card:
              - background-color: transparent
              - padding-bottom: 5px
              - padding-top: 0px
            grid:
              - grid-template-areas: |
                  "name gap"
              - grid-template-columns: 150px auto
              - grid-template-rows: 60px
              - column-gap: 0px
            main:
          custom_fields:
            name:
              card:
                type: custom:button-card
                show_state: false
                show_name: true
                show_icon: true
                show_label: false
                layout: icon_name
                icon: mdi:cog
                name: Settings
                size: 70%
                icon_color: var(--primary-text-color)
                styles: 
                  name: 
                    - font-size: 22px
                    - font-weight: bold
                  card:
                    - align-items: start
                    - justify-content: flex-start 
                    - text-align: left
                    - padding-left: 8px
      chips:
        card:
          type: custom:mushroom-chips-card
          card_mod:
            style: |
              ha-card {
                overflow: hidden !important;
              }
              ha-card > * {
                display: flex !important;
                flex-wrap: nowrap !important;
                overflow-x: auto !important;
                overflow-y: hidden !important;
                gap: 8px !important;
              }
              ha-card > * > * {
                flex-shrink: 0 !important;
              }
              /* More aggressive targeting */
              ha-card ::-webkit-scrollbar {
                height: 4px;
              }
              ha-card ::-webkit-scrollbar-track {
                background: transparent;
              }
              ha-card ::-webkit-scrollbar-thumb {
                background: rgba(255, 255, 255, 0.3);
                border-radius: 2px;
              }
              /* Try to target all possible chip containers */
              mushroom-chips,
              .chip-container,
              [class*="chip"] {
                display: flex !important;
                flex-wrap: nowrap !important;
                overflow-x: auto !important;
                overflow-y: hidden !important;
                width: 100% !important;
              }
              mushroom-chip,
              [class*="chip"]:not([class*="container"]) {
                flex-shrink: 0 !important;
                white-space: nowrap !important;
              }
          chips:
            - type: template
              content: Back
              tap_action:
                action: navigate
                navigation_path: /mobile-dash/mobile-home
              icon: mdi:chevron-left
              card_mod:
                style: |
                  :host {
                    zoom: 1.25 !important;
                    --chip-background: var(--background-color-2);
                  }
      settings:
        card:
          type: vertical-stack
          cards: !include mobile/settings-module.yaml